version: 2

before:
  hooks:
    - ./scripts/update-plugin-version.sh {{ .Tag }}

builds:
  - id: ralphex
    main: ./cmd/ralphex
    binary: ralphex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}

archives:
  - id: ralphex
    builds:
      - ralphex
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - completions/*

nfpms:
  - id: ralphex
    package_name: ralphex
    builds:
      - ralphex
    vendor: umputun
    homepage: https://github.com/umputun/ralphex
    maintainer: umputun
    description: Autonomous plan execution with Claude Code
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: completions/ralphex.bash
        dst: /usr/share/bash-completion/completions/ralphex
      - src: completions/ralphex.zsh
        dst: /usr/share/zsh/vendor-completions/_ralphex
      - src: completions/ralphex.fish
        dst: /usr/share/fish/vendor_completions.d/ralphex.fish

brews:
  - repository:
      owner: umputun
      name: homebrew-apps
    directory: Formula
    homepage: https://github.com/umputun/ralphex
    description: Autonomous plan execution with Claude Code
    license: MIT
    extra_install: |
      bash_completion.install "completions/ralphex.bash" => "ralphex"
      zsh_completion.install "completions/ralphex.zsh" => "_ralphex"
      fish_completion.install "completions/ralphex.fish" => "ralphex.fish"
